on: [push]

jobs:
  unsplash_stats_job:
    runs-on: ubuntu-latest
    name: A job to print Unsplash Stats
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Installing dependencies
      run: npm install

    # Collect and update markdown with Unsplash stats
    - name: Gathering Unsplash stats
      uses: ./
      with:
        file: './README.test.md'
        username: gabrieluizramos
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
    
    # Commit/Push to your repo after changing
    - name: Updating repo
      uses: EndBug/add-and-commit@v5
      with:
        add: './README.test.md'
        author_name: gabrieluizramos
        author_email: gabriel.luiz.ramos@gmail.com
        message: "README updated with Unsplash stats"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

